name: Semgrep AppSec

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  semgrep-analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: write

    container:
      image: semgrep/semgrep:1.158.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run Semgrep CI & Generate SARIF
        run: |
          semgrep ci \
            --sarif --sarif-output=semgrep.sarif \
            --config semgrep-config.yaml \
            --config semgrep-xss-rules.yaml \
            --include='*.java' || true
          if [ ! -s semgrep.sarif ]; then
            echo '{"version":"2.1.0","$schema":"https://json.schemastore.org/sarif-2.1.0.json","runs":[{"tool":{"driver":{"name":"semgrep"}},"results":[]}]}' > semgrep.sarif
          fi
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      # Uploads results to Security -> Code scanning alerts
      - name: Upload to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: semgrep.sarif
        if: always() # Upload results even if the scan fails or finds bugs

      # Makes the raw SARIF file available in the "Actions" run summary
      - name: Upload SARIF artifact
        uses: actions/upload-artifact@v6
        with:
          name: semgrep-sarif
          path: semgrep.sarif
        if: always()
